#language: ruby
#cache:
  #- bundler
#  - yarn
#services:
#  - mysql
#before_install:
#- mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
  #- nvm install --lts
#before_script:
#  - bundle install --jobs=3 --retry=3
  #- yarn
  #- bundle exec rake db:create
  #- bundle exec rake db:schema:load
#script:
  #- bundle exec rake test
  #- bundle exec rake test:system



language: ruby
env:
  - DB=mysql
script:
  - RAILS_ENV=test bundle exec rake db:create db:migrate db:seed --trace
  - bundle exec rspec test/

notifications:
  slack: lamgmt:8gk4DTVlhuQ42JDDnOZvLKKP

before_script:
  - cp config/database.travis.yml config/database.yml
bundler_args: --binstubs=./bundler_stubs
