language: ruby
env:
  - DB=mysql
script:
  - RAILS_ENV=test bundle exec rake db:create db:migrate db:seed --trace
  - rails test:system
  - brakeman -z
  - bundle-audit
notifications:
  slack:
    rooms:
      - lamgmt:8gk4DTVlhuQ42JDDnOZvLKKP
    on_success: never
    on_failure: always
before_script:
  - bundle
  - gem install brakeman
  - gem install bundle-audit
  - bundle-audit update
  - cp config/database.travis.yml config/database.yml
bundler_args: --binstubs=./bundler_stubs