name: Ruby
on: [ push, pull_request ]
jobs:
  system-test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.4
          bundler-cache: true
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Setup Rails
        run: |
          touch .ruby-version
          echo 2.6.4 >> .ruby-version
          cp Gemfile.ci Gemfile
          cp config/database.ci.yml config/database.yml
          bundle install --jobs 4 --retry 3
          gem install brakeman -v 5.0.0
          gem install bundle-audit -v 0.1.0
          RAILS_ENV=test bundle exec rake db:create db:migrate --trace
      - name: Run Test
        uses: nick-invision/retry@v2
        with:
          max_attempts: 3
          retry_wait_seconds: 30
          timeout_minutes: 15
          command: |
            rails test:system
            brakeman -z
            bundle-audit
